### ISSUE TITLE
Path param?

### ISSUE THREAD

**Issue by yohanboniface** [nitely/kua#2]
Given kua seems based on "/" split tree, I guess answer is "hardy", but: is supporting "path" variable somehow doable (i.e a variable that can contains `/`)?

For example: 

    routes.add('static/:path', {})
    routes.match('static/path/to.img')

**Comment by nitely** [comment]
Interesting. I don't use python for serving static files, so I've never thought of this. A sort of catch all would be certainly doable. It would require a special variable.

Based on your example something like this?:

```python
routes.add('static/*path', {})
routes.add('static/*path/foobar/:file_name', {})  # Static parts should match over wildcard vars

routes.match('static/path/to.img').params
# {'path': 'path/to.img'}
routes.match('static/path/sub-path/foobar/to.img').params
# {'file_name': 'to.img', 'path': 'path/sub-path'}
```

**Comment by yohanboniface** [comment]
>  I don't use python for serving static files

Only for development/debug ;)
For another example: http://werkzeug.pocoo.org/docs/0.12/routing/#werkzeug.routing.PathConverter

> Based on your example something like this?

Yep :)

**Comment by nitely** [comment]
Done!

Works like this:

```python
import kua

routes = kua.Routes()
routes.add('assets/:*foo', {})
route = routes.match('assets/user/profile/avatar.jpg')
route.params
# {'foo': ('user', 'profile', 'avatar.jpg')}

routes.add('assets/:*foo/:file_name', {})
route = routes.match('assets/user/profile/avatar.jpg')
route.params
# {'foo': ('user', 'profile'), 'file_name': 'avatar.jpg'}
```

Hopefully is more or less what you where expecting :sweat_smile:

**Comment by yohanboniface** [comment]
Nice, thanks!

Nit: I'd have done it that way `routes.add('assets/*:foo/:file_name', {})`, to prepare a possible typing enhancement like `routes.add('assets/str:foo/int:file_name', {})`, thoughts?

Also, FYI: https://framagit.org/drone/roll/issues/2#note_115051 Happy to have your inputs on this too :)

**Comment by yohanboniface** [comment]
Also, while I'm at it, what do you think about the [Routes](https://routes.readthedocs.io/en/latest/) api:

    map.connect("home", "/test/{param}", something="somevalue", somethingelse="foo")

I find it more pythonic to use kwargs instead of passing an explicit arg dict. Thoughts?

**Comment by nitely** [comment]
My ultimate goal is to provide the minimum API to build something more feature-rich on top of it. This is also why it's so generic (i.e: no attachments to any protocol). Default validators like `int:...` sounds cool, though.

```python
is_int = lambda var: var.isdigit()
routes.add(':var', {'GET': controller}, {'var': is_int})
routes.add('some/:var', {'GET': controller}, {'var': is_base64})
routes.add('some/more/:var', {'GET': controller}, {'var': regex(r'\w+')})
routes.add('profile/edit/:id', {'GET': profile_edit}, {'id': is_user_allowed})  # ????
```

Then you can change the semantics however you want:

```python
is_int = lambda var: var.isdigit()

def connect(name, pattern, controller, method):
    route = []
    validators = {}

    for part in pattern.split('/'):
        if part.startswith('{') and part.endswith('}'):
            part = ':%s' % part[1:-1]
        
        if part.startswith('int:'):
            part = ':%s' % part[4:]
            validators[part[4:]] = is_int

        if part.startswith('*:'):
            part = ':*%s' % part[2:]

        # so on...

        route.append(part)

    routes.add('/'.join(route), {method: controller}, validators)
```

**Comment by yohanboniface** [comment]
> My ultimate goal is to provide the minimum API to build something more feature-rich on top of it. This is also why it's so generic (i.e: no attachments to any protocol).

That's very nice goal, and that's why I'm using it :)

> def connect(name, pattern, controller, method):

I was not discussing the semantic, but suggesting to replace

    route.add('path/to/route", {'anything": "something"})

by:

    route.add('path/to/route", anything="something")

Which I personally found more pythonic, and in the spirit of this nice generic lib :)

**Comment by nitely** [comment]
> I find it more pythonic to use kwargs instead of passing an explicit arg dict. Thoughts?

You should definitely put a thin layer over kua to provide this. The dict thing is not really meant for consumers :yum: 

> Nit: I'd have done it that way routes.add('assets/*:foo/:file_name', {}), to prepare a possible typing enhancement like routes.add('assets/str:foo/int:file_name', {}), thoughts?

It's probably to late now since I went ahead and release the thing :sweat: . But if I end up adding the custom validators then yes looks more consistent that way.

> Also, FYI: https://framagit.org/drone/roll/issues/2#note_115051 Happy to have your inputs on this too :)

The URL reversing should be easy to implement and something I find very useful. The typed vars is comething I will implement, at the very least as described above (passing a func). About adding a more HTTP friendly API I dunno. A REST aware API would be ok I guess. About the async web server, I tried that not too long ago, ended it up creating [this thing](https://github.com/nitely/http-lazy-headers) but it's quite complex so I gave up haha.
