### ISSUE TITLE
Question about complex backtracking

### ISSUE THREAD

**Issue by b0g3r** [nitely/kua#9]
I have a [real-world API](https://advertising.amazon.com/API/docs/en-us/sponsored-products/2-0/openapi#/Reports/requestReport) and try to convert all paths to trie structure. But I have a problem with two similar patterns:

```python
import kua

routes = kua.Routes()
routes.add('/v2/sp/:recordType/report', 'report for record type')
routes.add('/v2/sp/keywords/:keywordId', 'keyword by keyword id')

# IRL should resolve into "report for record type"
routes.match('/v2/sp/keywords/report')
#  RouteResolved(params={'keywordId': 'report'}, anything='keyword by keyword id')
```

It looks like API spec isn't compatible with trie structure, but maybe you can propose some hacky way to do it?

**Comment by nitely** [comment]
that's an ambiguous API. Why would you expect it to match the first path? just because you registered it first?

This behavior is documented https://kua.readthedocs.io/en/latest/api.html#module-kua.routes

> Path parts are matched in the following order: static > var > any-var

**Comment by nitely** [comment]
> It looks like API spec isn't compatible with trie structure, but maybe you can propose some hacky way to do it?

There is no way without modifying the code and storing the registration order. Sadly, I don't think I'll ever modify this package.

There is a `feature/var_validate` branch that supports variables validation. I never merged it because I was not happy with the API, but it works well. See the tests cases. https://github.com/nitely/kua/pull/4

**Comment by nitely** [comment]
That branch supports:

```python
import kua

def is_int(var):
    return var.isdigit()

routes = kua.Routes()
routes.add('/v2/sp/:recordType/report', 'report for record type')
routes.add('/v2/sp/keywords/:keywordId', 'keyword by keyword id', {'keywordId': is_int})
routes.match('/v2/sp/keywords/report')
# RouteResolved(params={'recordType': 'keywords'}, anything='report for record type')
```

**Comment by b0g3r** [comment]
The `var_validate` feature looks great and could fix my problem. Could I expect release or it is better to use it as a direct "git branch" dependency?

**Comment by nitely** [comment]
I would say copy the Kua package into your project.
